#!/usr/bin/env python3

"""Compatibility entry point for the old extra asm generator.

The asm corpus is now generated by create_asm_tests.py as function-body tests
that exercise asm.c/asm.h. Keep this wrapper so older notes or shell history do
not recreate the previous top-level inline-asm fixtures.
"""

import create_asm_tests


if __name__ == "__main__":
    create_asm_tests.main()
